name: inject_creator_generator
description: inject_creator is a convenient code generator for get_it.
version: 0.0.1
homepage: https://github.com/wkcdeie/inject_creator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  source_gen: ^1.0.0
  inject_creator: ^0.0.1

dev_dependencies:
  build_runner: ^2.1.2
